import random

# --- Приветствия ---
GREETING_HOSTESS = "CAACAgIAAxkBAAIHj2iAChs6ubi63zrSCHd1wehShbDJAAJ2gwACLfIAAUgAAVT4KBDVr2Y2BA"
GREETING_TEAM = "CAACAgIAAxkBAAIHlWiACr5xbMv9tNQ49KymsksqOYYLAAIUgQACfZwAAUgcJKOgFuH9lTYE"
GREETING_CHEF = "CAACAgIAAxkBAAIHmWiAC1efwOzU8PXv1cpGP2IZ01BEAAN7AALN5wFI533VDdT1mHo2BA"
GREETING_WAITER = "CAACAgIAAxkBAAIHnGiAC3iUpaLbf_-H5J9czOn6997CAAKfggACV28AAUiiD8EOkiO0cTYE"

# --- Эмоции и действия ---
QUESTION_DOG = "CAACAgIAAxkBAAIHn2iAC5maCrWA69Cgrzfmcl4ZOeHPAAISgQACM0cAAUgQ_dl65aVWljYE"
FEEDBACK_SENT_DOG = "CAACAgIAAxkBAAIHomiAC85YGIm1_BbEF1NKi5gB3xSnAAKKgAAC3T8AAUjlRNKUgmsdrTYE"
ONBOARDING_INFO_DOG = "CAACAgIAAxkBAAIHpWiAC_VJG1TFQPhfztpeA5eXZflGAAIqjwAC8jABSBuofKT7h7gINgQ"
CONTACT_MANAGER = "CAACAgIAAxkBAAIHqGiADDZiFgfl-2wPnPD6XrYMB3RRAAKyhAAC5XABSOmbTsnxVW-RNgQ"
SUCCESS_DOG = "CAACAgIAAxkBAAIHq2iADFnw9MexQP_XPAMAAQzkjsZBAQACQYcAAmj5AUj2xzFdQF12uTYE"


# Список для случайного выбора приветственного стикера
GREETING_STICKERS = [GREETING_HOSTESS, GREETING_TEAM, GREETING_CHEF, GREETING_WAITER]

def get_random_greeting():
    """Возвращает ID случайного приветственного стикера."""
    return random.choice(GREETING_STICKERS)